// <auto-generated />
using Blazor.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BlazorApp.Persistencia.Migraciones
{
    [DbContext(typeof(AplicacionDbContext))]
    [Migration("20240515145634_MigracionInicial")]
    partial class MigracionInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Blazor.Persistencia.Formulario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Formulario");

                    b.HasData(
                        new
                        {
                            Id = 11,
                            Name = "Hola",
                            Password = "Messi@Gmail.com"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Holaxd",
                            Password = "Messixd@Gmail.com"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Holaxdxd",
                            Password = "Messi2xdxd@Gmail.com"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Holaxdxdxd",
                            Password = "Messi2xdxdxd@Gmail.com"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Holaxdxdxdxd",
                            Password = "Messi2xdxdxdxd@Gmail.com"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
